// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Item struct {
	ID       uuid.UUID
	Name     string
	Quantity int32
	Cost     int32
}

type ShoppingCart struct {
	ItemID   uuid.UUID
	UserID   uuid.UUID
	Quantity int32
	Cost     int32
	ItemName string
}

type User struct {
	ID             uuid.UUID
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Email          string
	HashedPassword string
}
